name: 'Hello_World_OneTwo333'
description: 'Greet someone'
author: 'nrd'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "Hello $INPUT_WHO_TO_GREET."
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}

    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: switch to action dir
      run: pwd
      working-directory: ${{env.GITHUB_ACTION_PATH}}
      shell: bash
      
    - name: Set Executable permission to script
      run: chmod +x goodbye.sh
      working-directory: ${{env.GITHUB_ACTION_PATH}}
      shell: bash 

    - name: Run goodbye.sh
      run: goodbye.sh
      working-directory: ${{env.GITHUB_ACTION_PATH}}
      shell: bash

